#site_name: Bót | Escrita Fiscal Automática
site_name: Bót
nav:
  - Instalação: index.md
  #- Perguntas/Respostas: perguntas-respostas.md
  #- Contato: contato.md
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/logo.png
  language: pt-BR
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tooltips
  font:
    text: Comic Sans
plugins:
  - blog
extra_css:
  - css.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: <a href="/blog" class="a_footer">Bót | Obrigações Tributárias Eireli</a> CNPJ 36.446.846/0001-05<br/>Atendemos contadores e escritórios de contabilidade
