site_name: Bót | Escrita Fiscal Terceirizada
nav:
  - Instalação: index.md
  #- O que é: o-que-e.md
theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/logo.png
  language: pt-BR
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tooltips
  font:
    text: Lora
markdown_extensions:
  - attr_list
copyright: Escrita Fiscal Terceirizada | Para contadores e escritórios de contabilidade.
